services:
  OpenVPN:
    image: 'kylemanna/openvpn:2.4'
    volumes:
      - "/var/docker/openvpn/data:/var/data_openvpn"
    ports:
      - "443:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: always/
