openvpn:
    image: "kylemanna/openvpn:2.4"
    container_name: openvpn
    ports:
        - "443:1194/udp"
    volumes:
        - "~/openvpn/data:/etc/openvpn"
    cap_add:
        - NET_ADMIN
    restart: always
