version: '3'

services:
  db :
    image : mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    container_name : mysql
    hostname: mysql
    restart: always
    ports :
      - 3306:3306
    volumes :
      - "/var/lib/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : toor
      MYSQL_DATABASE : ocsweb
    
    adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
   
    
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    networks:
            glpi_project:
    links :
      - mysql
    depends_on:
      - mysql
    environment:
      - TIMEZONE=Europe/Brussels
    volumes:
      - "/var/www/html/glpi/:/var/www/html/glpi"
    restart: always
    
networks:
  glpi_project:
