version: '3'

services: 
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    networks:
            glpi_project:
    links :
      - mysql
    depends_on:
      - mysql
    environment:
      - TIMEZONE=Europe/Brussels
    volumes:
      - "/var/www/html/glpi/:/var/www/html/glpi"
    restart: always
 
networks:
  glpi_project:

volumes:
  perlcomdata:
  extensionsdata:
  varlibdata:
  httpdconfdata:
  sqldata:
